on:
  workflow_dispatch:
  push:
    paths:
      - 'OX/**'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./OX
    steps:
      - uses: actions/checkout@v2
      - name: Run setup
        run: ./setup_linux.sh
      - name: Run PHPUnit tests
        run: php artisan test
