on:
  workflow_dispatch:
  push:
    paths:
      - 'OX/**'

jobs:
  # 1/1. lepes: Statikus analizis futtatasa.
  static-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./OX
    steps:
      - uses: actions/checkout@v2
      - name: Run setup
        run: |
          chmod +x ./setup_linux.sh
          ./setup_linux.sh
      - name: Run static analysis
        run: |
          chmod +x ./vendor/bin/phpstan
          ./vendor/bin/phpstan analyse --no-interaction --memory-limit=1G

  # 1/2. lepes: Linter futtatasa.
  linter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./OX
    steps:
      - uses: actions/checkout@v2
      - name: Run setup
        run: |
          chmod +x ./setup_linux.sh
          ./setup_linux.sh
      - name: Run static analysis
        run: |
          chmod +x ./vendor/bin/tlint
          ./vendor/bin/tlint lint app --no-interaction

  # 2. lepes: Unit testek futtatasa.
  unit-tests:
    needs: [static-analysis, linter]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./OX
    steps:
      - uses: actions/checkout@v2
      - name: Run setup
        run: |
          chmod +x ./setup_linux.sh
          ./setup_linux.sh
      - name: Run PHPUnit tests
        run: php artisan test
